# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 21:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('spotify_user', models.CharField(max_length=50)),
                ('genres', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
