# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 21:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapp_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genres',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
