# Generated by Django 2.1.7 on 2019-03-05 07:09

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapp_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('member_count', models.IntegerField()),
            ],
            options={
                'db_table': 'groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('spotify_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'membership',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=100)),
                ('genre', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('popularity', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('mode', models.IntegerField()),
                ('acousticness', models.FloatField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
            ],
            options={
                'db_table': 'songs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=20)),
                ('song_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'suggestions',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='spotify_user',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_id',
            field=models.CharField(default='default', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
